pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-backend') {
                    sh '''
                        mkdir -p .cache
                        mkdir -p .modcache
                        export GOCACHE=$(pwd)/.cache
                        export GOMODCACHE=$(pwd)/.modcache
                        go test -v ./...
                    '''
                }
            }
        }


        stage('Unit Tests - Frontend'){
            agent {
                docker {
                    image 'node:20-alpine'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-frontend'){
                    sh '''
                        npm ci
                        npm test                   

                    '''
                }
            }
            post {
                always {
                    junit 'bugtracker-frontend/test-results.xml'
                }
            }
        }
    }
}
