pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-backend') {
                    sh '''
                        mkdir -p .cache
                        mkdir -p .modcache
                        export GOCACHE=$(pwd)/.cache
                        export GOMODCACHE=$(pwd)/.modcache
                        go test -v ./... 2>&1 | go-junit-report > test-results.xml

                        # Generate coverage report
                        go test -coverprofile=coverage.out -covermode=atomic ./...
                        go tool cover -html=coverage.out -o coverage.html

                        mkdir -p reports
                        mv coverage.html reports/
                    '''
                }
            }
        }


        stage('Unit Tests - Frontend'){
            agent {
                docker {
                    image 'node:20-alpine'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-frontend'){
                    sh '''
                        npm ci
                        npm test  
                        mkdir -p reports
                        mv coverage reports/
                                         

                    '''
                }
            }
            post {
                always {
                    junit 'bugtracker-frontend/test-results.xml'
                    publishHTML target: [
                        reportDir: 'bugtracker-frontend/reports/coverage'
                        reportFiles: 'index.html'
                        reportName: 'Frontend Coverage Report'
                    ]
                }
            }
        }
    }
}
